matrix:
  - name: Markdown
    sources:
      - docs/en/preview/kubeblocks-for-**/**/*.mdx
    # - docs/en/preview/user_docs/concepts/**/*.mdx
    # - docs/en/preview/user_docs/overview/**/*.mdx
    # - docs/en/preview/user_docs/troubleshooting/**/*.mdx
    aspell:
      lang: en
      d: en_US
    dictionary:
      wordlists:
        - .wordlist-en.txt
      encoding: utf-8
    pipeline:
      - pyspelling.filters.markdown:
          markdown_extensions:
            - pymdownx.superfences:
            - pymdownx.tabbed:
      - pyspelling.filters.html:
          comments: false
          ignores:
            - code
            - pre
      - pyspelling.filters.url:
