name: Release Chart

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'The release version of helm chart'
        required: true
        default: ''
  release:
    types:
      - published

env:
  RELEASE_VERSION: ${{ github.ref_name }}
  GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

jobs:
  release-version:
    runs-on: ubuntu-latest
    outputs:
      release-version: ${{ steps.get_release_version.outputs.release_version }}
    steps:
      - name: Get Release Version
        id: get_release_version
        run: |
          RELEASE_VERSION=${{ inputs.release_version }}
          if [ -z "$RELEASE_VERSION" ]; then
              RELEASE_VERSION=${{ env.RELEASE_VERSION }}
          fi
          echo release_version=$RELEASE_VERSION >> $GITHUB_OUTPUT

  release-chart:
    needs: [ release-version ]
    uses: apecloud/apecloud-cd/.github/workflows/release-charts.yml@v0.1.86
    with:
      VERSION: "${{ needs.release-version.outputs.release-version }}"
      CHART_NAME: "kubeblocks-docs"
      CHART_DIR: "helm"
      APECD_REF: "v0.1.86"
    secrets: inherit
